# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_l2Iq_rKgpw86uTkcRpJb2UWROK3rVO
"""

!pip install -q streamlit
!pip install -q pyngrok

"""# Upload Your Model File (mobilenetv2_model.h5)"""

from google.colab import files
uploaded = files.upload()  # Upload your mobilenetv2_model.h5 here

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from tensorflow.keras.models import load_model
# from tensorflow.keras.preprocessing import image
# import numpy as np
# from PIL import Image
# 
# st.set_page_config(page_title="Brain Tumor Classification", layout="centered")
# st.title("🧠 Brain Tumor MRI Image Classifier")
# 
# @st.cache_resource
# def load_mymodel():
#     return load_model("mobilenetv2_model.h5")
# 
# model = load_mymodel()
# classes = ['glioma', 'meningioma', 'no_tumor', 'pituitary']
# 
# uploaded_file = st.file_uploader("📤 Upload an MRI Image", type=["jpg", "jpeg", "png"])
# 
# if uploaded_file is not None:
#     img = Image.open(uploaded_file).convert("RGB")
#     st.image(img, caption="Uploaded Image", use_column_width=True)
#     img = img.resize((224, 224))
#     img_array = image.img_to_array(img) / 255.0
#     img_array = np.expand_dims(img_array, axis=0)
#     prediction = model.predict(img_array)[0]
#     predicted_class = classes[np.argmax(prediction)]
#     confidence = np.max(prediction)
# 
#     st.markdown("### 🧪 Prediction Result")
#     st.success(f"**Tumor Type:** {predicted_class}")
#     st.info(f"**Confidence Score:** {confidence:.2f}")
#

"""# ngrok Authtoken"""

!ngrok config add-authtoken 30DBQOttrbcGRV1T3PUfDn0zt97_3K3DK6ri62cMtGXeokpGM

"""# Run the Streamlit Tunnel Cell"""

from pyngrok import ngrok

# Start Streamlit app in background
!streamlit run app.py &>/dev/null &

# Correct way to open ngrok tunnel (http URL, not just port)
public_url = ngrok.connect("http://localhost:8501")
print(f"Streamlit app is live at: {public_url}")